app = "ob-scanner-v2"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[env]
  TZ = "Europe/Paris"
  TELEGRAM_DRY_RUN = "true"
