#!/usr/bin/env python3
"""Success vs failure comparison, textbook audit, duplicates, and the pre-registered filter test.

Writes scripts/ob_shape/results/*.csv and results/REPORT_TABLES.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import fisher_exact, mannwhitneyu

HERE = Path(__file__).resolve().parent
RES = HERE / "results"
SPLIT = pd.Timestamp("2025-07-01", tz="UTC")
rng = np.random.default_rng(7)
md: list[str] = []

CONT = ["ob_body_ratio", "ob_prox_wick", "ob_dist_wick", "zone_h_atr", "risk_atr", "disp1_body_atr", "disp1_body_pct",
        "disp_maxbody_atr", "disp_n", "impulse3_atr", "fvg_atr", "bos_bars", "bos_margin_atr", "ob_to_bos_atr",
        "leg_gap", "leg_ext_beyond_atr", "opp_between", "leg_len_atr", "chop10", "chop20", "range20_atr",
        "touch_bars", "touch_after_bos", "run_after_bos_atr", "approach_bars", "approach_speed", "mom3_atr",
        "consec_toward", "prev_close_dist_atr", "touch_range_atr", "touch_body_atr", "tb_fails", "score"]
BIN = ["entry_mid", "sweep_leg", "ob_before_pivot", "gap_entry", "touch_big", "touch_close_through", "s2", "s3", "s4",
       "s5", "aligned_h4d1", "T1_displacement", "T2_fvg", "T3_bos_fast", "T4_bos_margin", "T5_origin", "T6_not_chop",
       "T7_body", "T8_size"]
AFTER_FILL = {"touch_range_atr", "touch_body_atr", "touch_big", "touch_close_through"}


def tbl(df: pd.DataFrame, title: str, floatfmt=3):
    md.append(f"\n### {title}\n")
    md.append(df.round(floatfmt).to_markdown(index=True))
    md.append("")


def compare(d: pd.DataFrame, label: str) -> pd.DataFrame:
    y = d[label]
    rows = []
    for f in CONT + BIN:
        if f not in d:
            continue
        x = pd.to_numeric(d[f], errors="coerce")
        ok = x.notna() & y.notna()
        a, b = x[ok & (y == 1)], x[ok & (y == 0)]
        if len(a) < 5 or len(b) < 5:
            continue
        if f in BIN:
            t = [[int((a == 1).sum()), int((a == 0).sum())], [int((b == 1).sum()), int((b == 0).sum())]]
            _, p = fisher_exact(t)
            n1 = (x[ok] == 1).sum()
            sr1 = y[ok & (x == 1)].mean() if n1 else np.nan
            sr0 = y[ok & (x == 0)].mean()
            rows.append(dict(feature=f, kind="bin", succ=a.mean(), fail=b.mean(), auc=np.nan, p=p,
                             note=f"succ-rate if 1: {sr1:.2f} (n={n1}) vs 0: {sr0:.2f} (n={(x[ok]==0).sum()})"))
        else:
            u, p = mannwhitneyu(a, b)
            rows.append(dict(feature=f, kind="cont", succ=a.median(), fail=b.median(), auc=u / (len(a) * len(b)),
                             p=p, note=""))
    r = pd.DataFrame(rows)
    r["after_fill"] = r.feature.isin(AFTER_FILL)
    return r


def boot_auc(x, y, n=500):
    x, y = np.asarray(x, float), np.asarray(y, int)
    ok = ~np.isnan(x)
    x, y = x[ok], y[ok]
    out = []
    for _ in range(n):
        i = rng.integers(0, len(x), len(x))
        a, b = x[i][y[i] == 1], x[i][y[i] == 0]
        if len(a) and len(b):
            out.append(mannwhitneyu(a, b).statistic / (len(a) * len(b)))
    return np.percentile(out, [2.5, 97.5])


def perf(g: pd.DataFrame, rcol="r_net"):
    r = g[rcol].dropna()
    n = len(r)
    if n == 0:
        return dict(n=0)
    se = r.std(ddof=1) / np.sqrt(n) if n > 1 else np.nan
    return dict(n=n, wr=(r > 0).mean(), avg=r.mean(), lo=r.mean() - 1.96 * se, hi=r.mean() + 1.96 * se)


def main():
    H = pd.read_parquet(RES / "hist_zones.parquet")
    P = pd.read_csv(RES / "prod_zones.csv")
    H["y_hold"] = np.where(H.hold == "tp", 1, np.where(H.hold == "sl", 0, np.nan))
    H["y_life"] = np.where(H.life == "reaction", 1, np.where(H.life == "echec", 0, np.nan))
    P["y_hold"] = np.where(P.hold == "tp", 1, np.where(P.hold == "sl", 0, np.nan))
    P["y_life"] = np.where(P.status == "reaction", 1, np.where(P.status == "echec", 0, np.nan))
    P["y_trade"] = np.where(P.trade_status == "closed", (P.trade_r > 0).astype(float), np.nan)
    H["period"] = np.where(H.ts_touch < SPLIT, "TRAIN", "TEST")

    # ---------------------------------------------------------------- A. samples
    md.append("# OB shape study — tables (generated by analyze.py)\n")
    a = P.groupby("tf").agg(n=("id", "size"), life_reaction=("y_life", "sum"), life_echec=("y_life", lambda s: (s == 0).sum()),
                            hold_tp=("hold", lambda s: (s == "tp").sum()), hold_sl=("hold", lambda s: (s == "sl").sum()),
                            hold_nofill=("hold", lambda s: (s == "nofill").sum()),
                            trade_closed=("trade_status", lambda s: (s == "closed").sum()),
                            trade_tp=("trade_exit", lambda s: (s == "tp").sum()),
                            trade_sl=("trade_exit", lambda s: (s == "sl").sum()),
                            trade_time=("trade_exit", lambda s: (s == "time").sum()),
                            trade_avgR=("trade_r", "mean"), alerted=("alerted", "sum"))
    tbl(a, "A1. Prod touched zones by TF (life = scanner status; hold = mid/open limit filled then +2R vs SL on TF bars; trade = prod trade_sim 1h, before costs)")
    b = H.groupby(["tf"]).agg(n=("sym", "size"), life_react=("y_life", "mean"), hold_tp=("y_hold", "mean"),
                              hold_n=("y_hold", "count"), sim_trades=("r_gross", "count"),
                              wr=("r_gross", lambda s: (s.dropna() > 0).mean()), r_gross=("r_gross", "mean"),
                              r_net=("r_net", "mean"), cost_r_med=("cost_r", "median"))
    tbl(b, "A2. Historical touched zones (2023-01→2026-09, 14 symbols) — rates are fractions")
    # phantom reactions
    ph = []
    for name, d, lab in (("prod", P, "status"), ("hist", H, "life")):
        r = d[d[lab] == "reaction"]
        ph.append(dict(sample=name, life_reactions=len(r), hold_tp=(r.hold == "tp").sum(), hold_sl=(r.hold == "sl").sum(),
                       hold_nofill=(r.hold == "nofill").sum(), share_real=(r.hold == "tp").mean()))
    tbl(pd.DataFrame(ph).set_index("sample"), "A3. 'Réaction +2R' (scanner status) vs what a resting entry limit actually got")

    # ---------------------------------------------------------------- C. feature comparison
    comps = {}
    for name, d, lab in (("prod_life", P, "y_life"), ("prod_hold", P, "y_hold"), ("prod_trade", P, "y_trade"),
                         ("hist_hold", H, "y_hold"), ("hist_life", H, "y_life"), ("hist_H1_hold", H[H.tf == "H1"], "y_hold")):
        c = compare(d, lab)
        c.insert(0, "sample", name)
        c["n_succ"] = int((d[lab] == 1).sum())
        c["n_fail"] = int((d[lab] == 0).sum())
        comps[name] = c
    allc = pd.concat(comps.values())
    allc.to_csv(RES / "feature_comparison.csv", index=False)
    for name in ("hist_hold", "prod_life", "prod_hold"):
        c = comps[name].copy()
        c["sep"] = np.where(c.kind == "cont", (c.auc - 0.5).abs(), np.nan)
        c = c.sort_values(["kind", "sep"], ascending=[True, False])
        tbl(c.set_index("feature")[["kind", "succ", "fail", "auc", "p", "after_fill", "note"]],
            f"C. {name}: success (n={c.n_succ.iloc[0]}) vs failure (n={c.n_fail.iloc[0]}) — medians (cont) / means (bin), AUC, Mann-Whitney/Fisher p")
    # bootstrap CI for a few AUCs in prod
    ci = []
    for f in ("ob_body_ratio", "zone_h_atr", "disp1_body_atr", "fvg_atr", "chop10", "bos_margin_atr", "approach_speed",
              "touch_bars", "tb_fails", "touch_body_atr"):
        for name, d, lab in (("prod_life", P, "y_life"), ("prod_hold", P, "y_hold")):
            dd = d[d[lab].notna()]
            lo, hi = boot_auc(dd[f], dd[lab])
            a1, b1 = dd[f][dd[lab] == 1].dropna(), dd[f][dd[lab] == 0].dropna()
            u = mannwhitneyu(a1, b1).statistic
            ci.append(dict(feature=f, sample=name, n=len(a1) + len(b1), auc=u / (len(a1) * len(b1)), lo=lo, hi=hi))
    tbl(pd.DataFrame(ci).set_index(["feature", "sample"]), "C2. Prod AUC with bootstrap 95% CI (0.5 = no separation)")

    # ---------------------------------------------------------------- D. buckets (hist)
    bk = []
    for f, bins in (("zone_h_atr", [0, .4, .6, .8, 1.0, 1.5, 99]), ("ob_body_ratio", [0, .25, .5, .75, 1.01]),
                    ("disp1_body_atr", [0, .5, 1, 1.5, 2, 99]), ("fvg_atr", [0, .1, .25, .5, 1, 99]),
                    ("chop10", [-1, 2, 4, 6, 8, 10]), ("bos_margin_atr", [-99, .1, .3, .6, 1, 99]),
                    ("approach_speed", [0, .2, .4, .7, 1.2, 99]), ("touch_bars", [0, 5, 10, 20, 50, 1e9]),
                    ("tb_fails", [-1, 0, 1, 2, 3, 9]), ("leg_gap", [-1, 0, 1, 3, 1e9]), ("cost_r", [0, .05, .1, .2, .4, 99])):
        g = H.assign(b=pd.cut(H[f], bins)).groupby("b", observed=True)
        t = g.agg(n=("sym", "size"), hold_tp=("y_hold", "mean"), life_react=("y_life", "mean"),
                  r_gross=("r_gross", "mean"), r_net=("r_net", "mean"))
        t.index = [f"{f} {i}" for i in t.index.astype(str)]
        bk.append(t)
    bk = pd.concat(bk)
    bk.to_csv(RES / "buckets_hist.csv")
    tbl(bk, "D. Historical buckets (all TFs; hold_tp breakeven for 2R = 0.333)")
    # categorical
    cat = []
    for f in ("tf", "group", "touch_session", "direction", "aligned_h4d1", "s2", "s3", "s4", "s5", "sweep_leg", "entry_mid", "gap_entry"):
        t = H.groupby(f).agg(n=("sym", "size"), hold_tp=("y_hold", "mean"), life_react=("y_life", "mean"),
                             r_gross=("r_gross", "mean"), r_net=("r_net", "mean"))
        t.index = [f"{f}={i}" for i in t.index]
        cat.append(t)
    cat = pd.concat(cat)
    cat.to_csv(RES / "categorical_hist.csv")
    tbl(cat, "E. Historical categorical splits")
    pc = []
    for f in ("tf", "group", "touched_session", "aligned_h4d1", "s2", "s3", "s4", "s5", "sweep_leg", "entry_mid"):
        t = P.groupby(P[f].astype(str)).agg(n=("id", "size"), life_react=("y_life", "mean"), hold_tp=("y_hold", "mean"),
                                            trades=("trade_r", "count"), trade_avgR=("trade_r", "mean"))
        t.index = [f"{f}={i}" for i in t.index]
        pc.append(t)
    tbl(pd.concat(pc), "E2. Prod categorical splits")

    # ---------------------------------------------------------------- F. textbook audit
    TB = ["T1_displacement", "T2_fvg", "T3_bos_fast", "T4_bos_margin", "T5_origin", "T6_not_chop", "T7_body", "T8_size"]
    PA = P[P.alerted == 1]
    rows = []
    for c in TB + ["NOT_TEXTBOOK(>=2 fails)"]:
        for name, d in (("hist", H), ("prod", P), ("prod_alerted", PA)):
            fail = (d.tb_fails >= 2) if c.startswith("NOT") else (d[c] == 0)
            ok = ~fail
            row = dict(criterion=c, sample=name, n=len(d), fail_share=fail.mean(),
                       hold_tp_fail=d.y_hold[fail].mean(), hold_tp_pass=d.y_hold[ok].mean(),
                       life_fail=d.y_life[fail].mean(), life_pass=d.y_life[ok].mean())
            if name == "hist":
                row.update(rgross_fail=d.r_gross[fail].mean(), rgross_pass=d.r_gross[ok].mean())
            else:
                row.update(rgross_fail=d.trade_r[fail].mean(), rgross_pass=d.trade_r[ok].mean())
            yy = d.y_hold
            t = [[int(((yy == 1) & fail).sum()), int(((yy == 0) & fail).sum())], [int(((yy == 1) & ok).sum()), int(((yy == 0) & ok).sum())]]
            row["fisher_p_hold"] = fisher_exact(t)[1]
            rows.append(row)
    tb = pd.DataFrame(rows).set_index(["criterion", "sample"])
    tb.to_csv(RES / "textbook_audit.csv")
    tbl(tb, "F. Textbook audit (fail_share = share of zones failing the criterion; prod rgross = trade_sim R before costs)")

    # ---------------------------------------------------------------- G. alerted zones
    cols = ["symbol", "tf", "direction", "ts_ob", "touched_at", "status", "hold", "trade_exit", "trade_r", "score",
            "zone_h_atr", "ob_body_ratio", "disp_maxbody_atr", "fvg_atr", "chop10", "bos_margin_atr", "leg_ext_beyond_atr",
            "approach_speed", "risk_pct", "tb_fails"] + TB
    PA[cols].to_csv(RES / "prod_alerted_zones.csv", index=False)
    tbl(PA[cols[:20]].set_index("symbol"), f"G. Zones really alerted on Telegram (n={len(PA)})", 3)

    # ---------------------------------------------------------------- H. duplicates / overlap (prod)
    P["t_touch"] = pd.to_datetime(P.touched_at, utc=True, format="ISO8601")
    P["cluster"] = -1
    cid = 0
    P_sorted = P.sort_values("t_touch")
    for i, z in P_sorted.iterrows():
        if P.at[i, "cluster"] >= 0:
            continue
        m = P[(P.symbol == z.symbol) & (P.direction == z.direction) & (P.low <= z.high) & (P.high >= z.low)
              & ((P.t_touch - z.t_touch).abs() <= pd.Timedelta(hours=6)) & (P.cluster < 0)]
        P.loc[m.index, "cluster"] = cid
        cid += 1
    cs = P.groupby("cluster").agg(k=("id", "size"), tfs=("tf", lambda s: ",".join(sorted(s))),
                                  alerted=("alerted", "sum"), react=("y_life", "sum"), echec=("y_life", lambda s: (s == 0).sum()))
    multi = cs[cs.k > 1]
    md.append(f"\n### H. Overlapping duplicates in prod\nZones in a multi-zone cluster (same symbol+side, overlapping price, touched within 6h): "
              f"**{int(multi.k.sum())}/{len(P)}** zones in {len(multi)} clusters; alerted zones in such clusters: "
              f"{int(P[(P.alerted == 1) & P.cluster.isin(multi.index)].shape[0])}/{len(PA)}. "
              f"Mixed outcome clusters (some reaction, some échec): {int(((multi.react > 0) & (multi.echec > 0)).sum())}.\n")
    md.append(multi.sort_values("k", ascending=False).head(15).to_markdown())
    P.to_csv(RES / "prod_zones_with_clusters.csv", index=False)

    # ---------------------------------------------------------------- I. filter test
    rules = {
        "baseline": lambda d: pd.Series(True, index=d.index),
        "R1 textbook (tb_fails<=1)": lambda d: d.tb_fails <= 1,
        "R2 slow approach (<=0.40 ATR/bar)": lambda d: d.approach_speed <= 0.40,
        "R3 cost_r<=0.10": lambda d: d.cost_r <= 0.10,
        "R2+R3": lambda d: (d.approach_speed <= 0.40) & (d.cost_r <= 0.10),
    }
    out = []
    T = H.dropna(subset=["r_net"])
    for tfsel in ("ALL", "H1", "M15", "M5", "M30", "H4"):
        G = T if tfsel == "ALL" else T[T.tf == tfsel]
        for per in ("TRAIN", "TEST"):
            g = G[G.period == per]
            for rn, f in rules.items():
                k = g[f(g)]
                pg, pn = perf(k, "r_gross"), perf(k, "r_net")
                row = dict(tf=tfsel, period=per, rule=rn, n=pn.get("n", 0), wr=pn.get("wr"), gross=pg.get("avg"),
                           net=pn.get("avg"), net_lo=pn.get("lo"), net_hi=pn.get("hi"))
                if rn != "baseline" and 5 <= len(k) < len(g):
                    sims = [g.r_net.sample(len(k), random_state=int(s)).mean() for s in rng.integers(0, 1e9, 1000)]
                    row["rand_p95_net"] = np.percentile(sims, 95)
                    row["pct_vs_random"] = (np.array(sims) < k.r_net.mean()).mean()
                out.append(row)
    ft = pd.DataFrame(out)
    ft.to_csv(RES / "filter_test.csv", index=False)
    tbl(ft[ft.tf.isin(["ALL", "H1"])].set_index(["tf", "period", "rule"]), "I. Pre-registered filter test (realistic sim; net = after per-asset costs)")
    tbl(ft[~ft.tf.isin(["ALL", "H1"]) & (ft.period == "TEST")].set_index(["tf", "period", "rule"]), "I2. Per-TF TEST")

    (RES / "REPORT_TABLES.md").write_text("\n".join(md))
    print("\n".join(md)[:200])


if __name__ == "__main__":
    main()
